from collections.abc import AsyncIterator
from typing import Any

from .plan import SchemaPlan

class OperationResult:
    """Result of a GraphQL operation with data, errors, and extensions."""

    data: dict[str, Any]
    errors: list[dict[str, Any]] | None
    extensions: dict[str, Any] | None
    def __repr__(self) -> str: ...
    def __getitem__(self, key: str) -> Any: ...

class Schema:
    def __init__(self, plan: SchemaPlan) -> None: ...
    async def execute(
        self, query: str, variables: dict[str, Any] | None = None, state: Any = None
    ) -> OperationResult | SubscriptionStream: ...
    def as_sdl(self) -> str: ...

class SubscriptionStream:
    def __aiter__(self) -> AsyncIterator[OperationResult]: ...
    async def __anext__(self) -> OperationResult: ...
    async def aclose(self) -> None: ...

class Graph:
    def requests(self, name: str) -> bool: ...
    def peek(self, name: str) -> Graph: ...
